### ISSUE TITLE
Can you provide the env of python?

### ISSUE THREAD

**Issue by kleinzcy** [kftam1994/Robo_Advisor#1]
Thanks for your code, but I can't run this code on my server. Can you provide the python env?

Thx.

**Comment by kftam1994** [comment]
Dear kleinzcy,

Thanks for your enquiry. The Python environment is Python 3.6 and the following are the major packages
numpy                     1.19.5
pandas                    0.22.0
pytorch                   1.8.1
tensorboard               2.4.1
yahoofinancials           1.6
optuna                    2.8.0
ta-lib                    0.4.19
zipline                   1.4.1

Would you mind sharing the error messages you are facing?

Thank you

**Comment by kleinzcy** [comment]
@kftam1994 Thanks for your help, I have solved the environmental conflict. In addition, the code is well written, and I have benefited a lot from it. 

Best wishes,
klein
