### ISSUE TITLE
Can you provide the data you download?

### ISSUE THREAD

**Issue by kleinzcy** [kftam1994/Robo_Advisor#2]
Sorry to bother you again.

For some reason, I can't download the data from yahoo. So, can you provide the data which will be used in the training? (Google Drive, Dropbox, BaiDuYun or anything else)

Thanks very much if you can help me.

Best wishes,
Klein

**Comment by kftam1994** [comment]
Hi Klein,

Sorry for late reply. I was changing to a new computer last month.
I just tried the code preparing data. It works.
Would you mind sharing the error messages?

Best regards,
Andy

**Comment by kleinzcy** [comment]
@kftam1994 Hi, Andy,

Thanks for your reply, I have solved the problem. 

Thanks again for your nice code.

Best regards,
Klein
